#!/bin/bash

# Refresh the local iris-core and rerun any necessary setups

source_dir=$PKG_DIR
script_loc=$(dirname $0)
scope="remote" # gets passed to setup scripts telling to pull any git repos

. $script_loc/update_functions.sh

if [[ "$#" -ge 1 ]]; then

	if handle_common_help_args $@; then
		exit
	fi

	update_iris_core
	if [[ "$1" == "all" ]]; then
		update_all
	else
		update_specific $1
	fi
	exit
fi

update_iris_core
update_default
