#!/bin/bash

# Run specific setups from designated source location (can be used for testing alternate installations without pushing to global repo)

source_dir=$LAB_DIR 
script_loc=$(dirname $0)
scope="local" # gets passed to setup scripts saying pulling is not necessary

. $script_loc/update_functions.sh


if [[ "$#" -ge 1 ]]; then

	if handle_common_help_args $@; then
		exit
	fi
	
	if [[ "$1" == "source" ]]; then
		source_dir=$2
		
	elif [[ "$1" == "all" ]]; then
		if [[ "$2" == "source" ]]; then
			source_dir=$3
		fi
		
		update_all
		exit
	else
		if [[ "$2" == "source" ]]; then
			source_dir=$3
		fi
		
		update_specific $1
		exit
	fi
fi

update_default
