#!/bin/bash

# Refresh the local iris-core and rerun any necessary setups

setup_list=$DATA_DIR/iris/setup_list

# TODO: should really generalize/extract/abstract commonalities between this and the update script
# TODO: this should also be settable via cmdline
source_dir=$LAB_DIR 


if [[ "$#" -ge 1 ]]; then
	if [[ "$1" == "help" ]]; then
		# TODO: 
		echo "TODO:"

		echo -e "\n\nConfigured setups:"
		cat $setup_list
		exit
	elif [[ "$1" == "ls" || "$1" == "list" ]]; then
		cat "$setup_list"
		exit
	elif [[ "$1" == "source" ]]; then
		source_dir=$2
	else
		if [[ "$2" == "source" ]]; then
			source_dir=$3
		fi
		
		echo "Update of $1 requested..."
		bash $source_dir/iris-core/setups/$1.sh
		exit
	fi
fi

echo "Rerunning all prior setups..."

while IFS="" read -r setup || [ -n "$setup" ]
do
	echo "Setting up $setup..."
	bash $source_dir/iris-core/setups/$setup.sh
done < $setup_list
